#cloud-config
hostname: nginx-support-node
timezone: America/Vancouver
users:
  - name: sofien
    groups: [adm, cdrom, dip, plugdev, lxd, sudo, users]
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGXTmFRDd3T5TfSIcD3RAc494p6zoPeVWCnlaf9h3glA sengodwin@gmail.com
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: $6$FdiKwe9zh/3utVGB$PWkWze/2b0b50fC1EiPRT5WXjCey/V9wL8TQzIoCAkYuD9G2FGXHSukQPw6oPK3EpNhEQ04gmVD4X5BIKggBf.
package_update: true
packages:
  - qemu-guest-agent
  - net-tools
  - curl
  - nginx
write_files:
  - path: /tmp/cloud.cloud
    content: From cloud config
  - path: nginx.conf
    content: |
      events {}
            
            stream {
              upstream k3s_servers {
                server 191.168.1.205:6443;
                server 191.168.1.206:6443;
                server 191.168.1.207:6443;
              }
            
              server {
                listen 6443;
                proxy_pass k3s_servers;
              }
            }
  - path: /var/www/html/index.html
    content: |
      <html>
        <head><title>Welcome to NGINX!</title></head>
        <body>
          <h1>NGINX installed via cloud-init 🚀</h1>
          <p>Instance: $(hostname)</p>
        </body>
      </html>
runcmd:
  - systemctl enable --now qemu-guest-agent
  - systemctl start qemu-guest-agent
  - echo "done" > /tmp/cloud-config.done
  - systemctl start nginx
  - cp nginx.conf /etc/nginx/nginx.conf
  - echo "done" > /tmp/cloud-config.done